# Generated by Django 3.2.6 on 2021-11-01 06:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='matchmodel',
            name='user',
        ),
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.DeleteModel(
            name='GoodModel',
        ),
        migrations.DeleteModel(
            name='MatchModel',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
    ]
