# Generated by Django 3.2.6 on 2021-11-01 06:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sofutomoapp', '0002_auto_20211101_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, default=0, null=True)),
                ('genre', models.CharField(blank=True, max_length=30)),
                ('address', models.CharField(blank=True, max_length=30)),
                ('artist', models.CharField(blank=True, max_length=30)),
                ('part', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(upload_to='')),
                ('good_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='good_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
