# Generated by Django 3.2.6 on 2021-11-01 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sofutomoapp', '0003_goodmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bandmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='goodmodel',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='userinfo',
            name='name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
