# Generated by Django 3.2.6 on 2021-11-02 09:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sofutomoapp', '0004_auto_20211101_1708'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True, max_length=1000, null=True, verbose_name='')),
                ('cm_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_user', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cm_user_1', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
